<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PaymentMethod;
use Illuminate\Support\Facades\DB;

class PaymentMethodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data yang ada terlebih dahulu jika perlu
        // DB::table('payment_methods')->truncate();

        $methods = [
            [
                'code' => 'credit_card',
                'name' => 'Kartu Kredit',
                'type' => 'credit_card',
                'bank_code' => null,
                'fee_percentage' => 2.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/credit-card.png',
                'instructions' => 'Pembayaran dengan kartu kredit Visa/Mastercard. Kami mendukung pembayaran cicilan 0% untuk tenor tertentu.',
                'midtrans_payment_type' => 'credit_card',
                'sort_order' => 1,
            ],
            [
                'code' => 'bca_va',
                'name' => 'BCA Virtual Account',
                'type' => 'bank_transfer',
                'bank_code' => 'bca',
                'fee_percentage' => 0,
                'fee_flat' => 4000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/bca.png',
                'instructions' => 'Transfer ke BCA Virtual Account. Tersedia di m-BCA, BCA mobile, atau internet banking BCA.',
                'midtrans_payment_type' => 'bank_transfer',
                'sort_order' => 2,
            ],
            [
                'code' => 'bni_va',
                'name' => 'BNI Virtual Account',
                'type' => 'bank_transfer',
                'bank_code' => 'bni',
                'fee_percentage' => 0,
                'fee_flat' => 4000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/bni.png',
                'instructions' => 'Transfer ke BNI Virtual Account. Tersedia di BNI mobile banking atau internet banking BNI.',
                'midtrans_payment_type' => 'bank_transfer',
                'sort_order' => 3,
            ],
            [
                'code' => 'mandiri_va',
                'name' => 'Mandiri Virtual Account',
                'type' => 'bank_transfer',
                'bank_code' => 'mandiri',
                'fee_percentage' => 0,
                'fee_flat' => 4000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/mandiri.png',
                'instructions' => 'Transfer melalui Livin\' by Mandiri. Pilih menu Bayar > Multi Payment > Cari Midtrans.',
                'midtrans_payment_type' => 'echannel',
                'sort_order' => 4,
            ],
            [
                'code' => 'bri_va',
                'name' => 'BRI Virtual Account',
                'type' => 'bank_transfer',
                'bank_code' => 'bri',
                'fee_percentage' => 0,
                'fee_flat' => 4000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/bri.png',
                'instructions' => 'Transfer ke BRI Virtual Account. Tersedia di BRImo atau internet banking BRI.',
                'midtrans_payment_type' => 'bank_transfer',
                'sort_order' => 5,
            ],
            [
                'code' => 'permata_va',
                'name' => 'Permata Virtual Account',
                'type' => 'bank_transfer',
                'bank_code' => 'permata',
                'fee_percentage' => 0,
                'fee_flat' => 4000,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/permata.png',
                'instructions' => 'Transfer ke Permata Virtual Account. Tersedia di PermataMobile X atau internet banking Permata.',
                'midtrans_payment_type' => 'bank_transfer',
                'sort_order' => 6,
            ],
            [
                'code' => 'gopay',
                'name' => 'GoPay',
                'type' => 'ewallet',
                'bank_code' => null,
                'fee_percentage' => 1.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/gopay.png',
                'instructions' => 'Gunakan aplikasi Gojek untuk melakukan pembayaran. Scan QR code atau gunakan kode pembayaran.',
                'midtrans_payment_type' => 'gopay',
                'sort_order' => 7,
            ],
            [
                'code' => 'shopeepay',
                'name' => 'ShopeePay',
                'type' => 'ewallet',
                'bank_code' => null,
                'fee_percentage' => 1.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/shopeepay.png',
                'instructions' => 'Gunakan aplikasi Shopee untuk melakukan pembayaran melalui ShopeePay.',
                'midtrans_payment_type' => 'shopeepay',
                'sort_order' => 8,
            ],
            [
                'code' => 'dana',
                'name' => 'DANA',
                'type' => 'ewallet',
                'bank_code' => null,
                'fee_percentage' => 1.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/dana.png',
                'instructions' => 'Gunakan aplikasi DANA untuk melakukan pembayaran. Scan QR code atau gunakan kode pembayaran.',
                'midtrans_payment_type' => 'qris',
                'sort_order' => 9,
            ],
            [
                'code' => 'ovo',
                'name' => 'OVO',
                'type' => 'ewallet',
                'bank_code' => null,
                'fee_percentage' => 1.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/ovo.png',
                'instructions' => 'Gunakan aplikasi OVO untuk melakukan pembayaran. Scan QR code atau gunakan kode pembayaran.',
                'midtrans_payment_type' => 'qris',
                'sort_order' => 10,
            ],
            [
                'code' => 'linkaja',
                'name' => 'LinkAja',
                'type' => 'ewallet',
                'bank_code' => null,
                'fee_percentage' => 1.5,
                'fee_flat' => 2000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/linkaja.png',
                'instructions' => 'Gunakan aplikasi LinkAja untuk melakukan pembayaran. Scan QR code atau gunakan kode pembayaran.',
                'midtrans_payment_type' => 'qris',
                'sort_order' => 11,
            ],
            [
                'code' => 'qris',
                'name' => 'QRIS',
                'type' => 'qris',
                'bank_code' => null,
                'fee_percentage' => 0.7,
                'fee_flat' => 0,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/qris.png',
                'instructions' => 'Scan QR code dengan aplikasi e-wallet atau mobile banking yang mendukung QRIS.',
                'midtrans_payment_type' => 'qris',
                'sort_order' => 12,
            ],
            [
                'code' => 'indomaret',
                'name' => 'Indomaret',
                'type' => 'cstore',
                'bank_code' => null,
                'fee_percentage' => 0,
                'fee_flat' => 5000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/indomaret.png',
                'instructions' => 'Bayar di kasir Indomaret dengan kode pembayaran yang diberikan. Simpan struk sebagai bukti pembayaran.',
                'midtrans_payment_type' => 'cstore',
                'sort_order' => 13,
            ],
            [
                'code' => 'alfamart',
                'name' => 'Alfamart',
                'type' => 'cstore',
                'bank_code' => null,
                'fee_percentage' => 0,
                'fee_flat' => 5000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/alfamart.png',
                'instructions' => 'Bayar di kasir Alfamart dengan kode pembayaran yang diberikan. Simpan struk sebagai bukti pembayaran.',
                'midtrans_payment_type' => 'cstore',
                'sort_order' => 14,
            ],
            [
                'code' => 'alfamidi',
                'name' => 'Alfamidi',
                'type' => 'cstore',
                'bank_code' => null,
                'fee_percentage' => 0,
                'fee_flat' => 5000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/alfamidi.png',
                'instructions' => 'Bayar di kasir Alfamidi dengan kode pembayaran yang diberikan. Simpan struk sebagai bukti pembayaran.',
                'midtrans_payment_type' => 'cstore',
                'sort_order' => 15,
            ],
            [
                'code' => 'deposit',
                'name' => 'Saldo Deposit',
                'type' => 'deposit',
                'bank_code' => null,
                'fee_percentage' => 0,
                'fee_flat' => 0,
                'minimum_amount' => 10000,
                'maximum_amount' => 50000000,
                'is_active' => true,
                'icon' => 'payment/deposit.png',
                'instructions' => 'Gunakan saldo deposit Anda untuk membayar transaksi. Pastikan saldo mencukupi.',
                'midtrans_payment_type' => null,
                'sort_order' => 16,
            ],
            [
                'code' => 'cod',
                'name' => 'Cash on Delivery',
                'type' => 'cod',
                'bank_code' => null,
                'fee_percentage' => 5,
                'fee_flat' => 10000,
                'minimum_amount' => 10000,
                'maximum_amount' => 5000000,
                'is_active' => true,
                'icon' => 'payment/cod.png',
                'instructions' => 'Bayar tunai saat barang diterima. Hanya tersedia untuk area tertentu dengan tambahan biaya layanan.',
                'midtrans_payment_type' => null,
                'sort_order' => 17,
            ],
        ];

        foreach ($methods as $method) {
            // Gunakan updateOrCreate untuk menghindari duplicate entry
            PaymentMethod::updateOrCreate(
                ['code' => $method['code']], // Cari berdasarkan code
                $method // Data yang akan diupdate/dibuat
            );
        }

        $this->command->info('Payment methods seeded successfully. Total: ' . count($methods));
    }
}